apiVersion: apps/v1
kind: Deployment
metadata:
  name: solv-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: solv-app
  template:
    metadata:
      labels:
        app: solv-app
    spec:
      containers:
        - name: solv-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
