# ===========================
# Kubernetes Deployment for SOLV Application
# ===========================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: solv-app  # Name of the deployment

spec:
  replicas: {{ .Values.replicaCount }}  # Number of pod replicas, set in values.yaml

  selector:
    matchLabels:
      app: solv-app  # Ensures only pods with this label are selected

  template:
    metadata:
      labels:
        app: solv-app  # Labels for pods, must match the selector labels

    spec:
      containers:
        - name: solv-app  # Container name within the pod

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"  
          # Pulls the container image from the repository and tag defined in values.yaml

          ports:
            - containerPort: 80  # Exposes the container on port 80

          resources:
            limits:
              cpu: 500m      # Maximum CPU limit for the container
              memory: 512Mi  # Maximum memory limit for the container

            requests:
              cpu: 250m      # Minimum CPU request (ensures enough resources are allocated)
              memory: 256Mi  # Minimum memory request
