apiVersion: v1
kind: Service
metadata:
  name: solv-app-service
spec:
  selector:
    app: solv-app
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
