replicaCount: 2

image:
  repository: ${{ secrets.DOCKERHUB_USERNAME }}/solv-app
  tag: "latest"

service:
  type: LoadBalancer
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
