# ===========================
# GitHub Actions Workflow - Deploy to Existing AWS EKS
# ===========================

name: Deploy to AWS EKS  # Workflow name

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]  # Runs only after the CI workflow completes
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  
        # Pulls the latest code from the repository

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1  
        # Configures AWS CLI using GitHub Secrets
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Ensure this matches the pre-configured EKS region

      - name: Update kubeconfig to use existing EKS cluster
        run: |
          aws eks update-kubeconfig --name solv-cluster --region us-east-1  
          # Ensures `kubectl` commands target the existing cluster

      - name: Deploy Application to Kubernetes
        run: |
          kubectl apply -f helm/templates/deployment.yaml  
          kubectl apply -f helm/templates/service.yaml  
          # Deploys the application to the existing EKS cluster

      - name: Deploy Monitoring Tools
        run: |
          kubectl apply -f helm/templates/monitoring.yaml  
          # Deploys observability tools (Prometheus, Grafana, Kiali, Celery) into EKS
